import type { Metadata } from "next";

import "@/styles/_global.scss";
import "@/styles/_layout.scss";

import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <svg
          className="background-img first"
          viewBox="0 0 200 200"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            fill="#FF3333"
            d="M51,-50.5C66.9,-35.1,81.2,-17.6,80.5,-0.8C79.7,16,63.9,32.1,48,46.6C32.1,61.1,16,74,-0.8,74.8C-17.6,75.6,-35.2,64.2,-46.6,49.7C-58,35.2,-63.1,17.6,-62,1.1C-60.9,-15.4,-53.5,-30.8,-42.2,-46.2C-30.8,-61.7,-15.4,-77.1,1.1,-78.2C17.6,-79.3,35.1,-66,51,-50.5Z"
            transform="translate(100 100)"
          />
        </svg>
        <svg
          className="background-img second"
          viewBox="0 0 200 200"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            fill="#FF3333"
            d="M59.8,-58.7C74,-45.5,79.9,-22.7,75.2,-4.7C70.5,13.4,55.3,26.7,41,38.6C26.7,50.4,13.4,60.6,-1.1,61.7C-15.6,62.9,-31.2,54.8,-46.9,43C-62.6,31.2,-78.4,15.6,-82.1,-3.7C-85.9,-23.1,-77.6,-46.2,-61.9,-59.4C-46.2,-72.6,-23.1,-76,-0.2,-75.8C22.7,-75.6,45.5,-71.9,59.8,-58.7Z"
            transform="translate(100 100)"
          />
        </svg>
        <svg
          className="background-img third"
          viewBox="0 0 200 200"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            fill="#FF3333"
            d="M51.7,-52.2C64.8,-38.6,71.8,-19.3,71.2,-0.5C70.7,18.2,62.6,36.4,49.5,50.6C36.4,64.9,18.2,75.1,-2.3,77.5C-22.8,79.8,-45.7,74.1,-60.2,59.9C-74.8,45.7,-81.2,22.8,-75.7,5.4C-70.3,-11.9,-53,-23.9,-38.5,-37.5C-23.9,-51.1,-11.9,-66.5,3.7,-70.2C19.3,-73.8,38.6,-65.9,51.7,-52.2Z"
            transform="translate(100 100)"
          />
        </svg>
        <svg
          className="background-img fourth"
          viewBox="0 0 200 200"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            fill="#FF3333"
            d="M45.2,-41.2C61.6,-28.9,79.9,-14.4,78.7,-1.2C77.5,12,56.7,24,40.3,31.3C24,38.6,12,41.2,-0.3,41.4C-12.5,41.7,-25,39.6,-35.4,32.3C-45.8,25,-54.2,12.5,-56.6,-2.5C-59.1,-17.4,-55.7,-34.8,-45.2,-47.2C-34.8,-59.6,-17.4,-66.9,-1.5,-65.4C14.4,-63.9,28.9,-53.6,45.2,-41.2Z"
            transform="translate(100 100)"
          />
        </svg>
        <Navbar />
        <div className="page-content">{children}</div>
      </body>
    </html>
  );
}
