import type { Metadata } from "next";
import "@/styles/global.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <nav className="navbar">
          <a href="/" className="navbar-element logo">
            GuildHub
          </a>
          <a href="/features" className="navbar-element">
            Features
          </a>
          <a href="/faq" className="navbar-element">
            FAQ
          </a>
          <a href="/pricing" className="navbar-element">
            Pricing
          </a>
          <a href="/login" className="navbar-element"></a>
        </nav>
        {children}
      </body>
    </html>
  );
}
