import type { Metadata } from "next";

import "@/styles/_global.scss";
import "@/styles/_layout.scss";

import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <div className="page-content">{children}</div>
      </body>
    </html>
  );
}
